
import { Movie, Genre } from './types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: "1",
    title: "The Walking Dead",
    description: "A Heaps prisoner makes a discovery; Carol searches for someone in the nearby forest; Rick and Morgan find themselves in the company of strangers.",
    longDescription: "Set after a zombie apocalypse, the series follows a group of survivors, led by former police officer Rick Grimes, who travel in search of a safe and secure home. As they navigate a world overrun by the dead, they face challenges from not only the zombies but also from other human survivors.",
    posterUrl: "https://picsum.photos/seed/twdposter/200/300",
    bannerUrl: "https://picsum.photos/seed/twdbanner/1280/720",
    duration: "51m",
    rating: 7.5,
    year: 2018, // Example year for this specific episode/season info
    genres: ["Drama", "Horror", "Thriller"],
    trailerUrl: "https://www.youtube.com/embed/R1v0uFms68U", // Generic TWD trailer
    googleDriveLink: "https://media.verif323cloud.cfd/file.zip?c=AOTFTmiKcwUA_YUCAElOFwASAAAAAAAf&s=357258", // Example link
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4", // Placeholder video
    isFeatured: true,
    ageRating: "16+",
    type: "series",
    seasonEpisodeInfo: "Season 9 - Episode 14 - Still Gotta Mean Something",
  },
  {
    id: "2",
    title: "Pacific Rim: Uprising",
    description: "Jake Pentecost, son of Stacker Pentecost, reunites with Mako Mori to lead a new generation of Jaeger pilots against a new Kaiju threat.",
    posterUrl: "https://picsum.photos/seed/pacificrim/200/300",
    bannerUrl: "https://picsum.photos/seed/pacificrimbanner/1280/720",
    duration: "1h 51m",
    rating: 5.8,
    year: 2018,
    genres: ["Action", "Sci-Fi", "Adventure"],
    trailerUrl: "https://www.youtube.com/embed/8BAhwgjffP4",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-2",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "13+",
  },
  {
    id: "3",
    title: "Star Wars: Solo",
    description: "During an adventure into a dark criminal underworld, Han Solo meets his future copilot Chewbacca and encounters Lando Calrissian years before joining the Rebellion.",
    posterUrl: "https://picsum.photos/seed/solo/200/300",
    bannerUrl: "https://picsum.photos/seed/solobanner/1280/720",
    duration: "2h 15m",
    rating: 7.2,
    year: 2018,
    genres: ["Action", "Adventure", "Sci-Fi"],
    trailerUrl: "https://www.youtube.com/embed/jPEYpryMp2s",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-3",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "13+",
  },
  {
    id: "4",
    title: "Red Sparrow",
    description: "Ballerina Dominika Egorova is recruited to 'Sparrow School,' a Russian intelligence service where she is forced to use her body as a weapon.",
    posterUrl: "https://picsum.photos/seed/redsparrow/200/300",
    bannerUrl: "https://picsum.photos/seed/redsparrowbanner/1280/720",
    duration: "2h 20m",
    rating: 6.6,
    year: 2018,
    genres: ["Drama", "Thriller", "Mystery"],
    trailerUrl: "https://www.youtube.com/embed/Z_Y22sJei_M",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-4",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "18+",
  },
  {
    id: "5",
    title: "Jurassic World: Fallen Kingdom",
    description: "When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
    longDescription: "Three years after the destruction of the Jurassic World theme park, Owen Grady and Claire Dearing return to the island of Isla Nublar to save the remaining dinosaurs from a volcano that's about to erupt. They soon encounter terrifying new breeds of gigantic dinosaurs, while uncovering a conspiracy that threatens the entire planet.",
    posterUrl: "https://picsum.photos/seed/jurassicworld/200/300",
    bannerUrl: "https://picsum.photos/seed/jurassicworldbanner/1280/720",
    duration: "2h 08m",
    rating: 8.3,
    year: 2018,
    genres: ["Action", "Adventure", "Sci-Fi"],
    trailerUrl: "https://www.youtube.com/embed/vn9mMeWcgoQ",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-5",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "13+",
  },
  {
    id: "6",
    title: "Deadpool 2",
    description: "Foul-mouthed mutant mercenary Wade Wilson (AKA. Deadpool), brings together a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg Cable.",
    posterUrl: "https://picsum.photos/seed/deadpool2/200/300",
    bannerUrl: "https://picsum.photos/seed/deadpool2banner/1280/720",
    duration: "1h 59m",
    rating: 8.1,
    year: 2018,
    genres: ["Action", "Comedy", "Adventure"],
    trailerUrl: "https://www.youtube.com/embed/D86RtevtfrA",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-6",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "16+",
  },
   {
    id: "7",
    title: "The Meg",
    description: "A group of scientists exploring the Mariana Trench encounter the largest marine predator that has ever existed - the Megalodon.",
    posterUrl: "https://picsum.photos/seed/themeg/200/300",
    bannerUrl: "https://picsum.photos/seed/themegbanner/1280/720",
    duration: "1h 53m",
    rating: 6.4,
    year: 2018,
    genres: ["Action", "Horror", "Sci-Fi"],
    trailerUrl: "https://www.youtube.com/embed/udm5jUA-2bs",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-7",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "13+",
  },
  {
    id: "8",
    title: "Incredibles 2",
    description: "The Incredibles hero family takes on a new mission, which involves a change in family roles: Bob Parr (Mr Incredible) must manage the house while his wife Helen (Elastigirl) goes out to save the world.",
    posterUrl: "https://picsum.photos/seed/incredibles2/200/300",
    bannerUrl: "https://picsum.photos/seed/incredibles2banner/1280/720",
    duration: "1h 58m",
    rating: 7.7,
    year: 2018,
    genres: ["Animation", "Action", "Adventure"],
    trailerUrl: "https://www.youtube.com/embed/i5qOzqD9Rms",
    googleDriveLink: "https://docs.google.com/uc?export=download&id=1exemplespreadsheetId-for-download-8",
    videoSrc: "https://www.w3schools.com/html/mov_bbb.mp4",
    type: "movie",
    ageRating: "PG",
  },
];

export const GENRES_LIST: Genre[] = ["Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "History", "Horror", "Music", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"];
